# -*- coding: utf-8 -*-
"""Copy of Amritanshi and Team

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/10MHMbEw5skfQCEUXOedd1OXlP7eClrP4
"""

!pip install openai

import pandas as pd
import re

from tqdm.notebook import tqdm
from openai import OpenAI
import json
import numpy as np

from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, balanced_accuracy_score, f1_score, precision_score, recall_score, confusion_matrix
from sklearn.ensemble import RandomForestClassifier, GradientBoostingClassifier

SECRET_KEY = "Enter your key"

"""Load the dataset from a Google sheet."""

# # CHANGE THIS IF YOU WANT
GOOGLE_SPREADSHEET_LINK = "https://docs.google.com/spreadsheets/d/1qwT7QnykOQ6vgnf2g2JsXTMrqEgxXsLo5KpvgdPtrm4/edit?usp=sharing"

sheet_id = GOOGLE_SPREADSHEET_LINK.split("/")[5]

url=f'https://docs.google.com/spreadsheet/ccc?key={sheet_id}&output=xlsx'
dataset = pd.read_excel(url, sheet_name="Sheet2")
dataset

"""Convert the dataset to the GPT format. Modify the prompt below."""

def apply_prompt_template(sample, test=False):
  question = sample["question"]

  prompt = f"""Given the following GMAT questions:

{{question}}

For each of these official gmat questions, give me gamified versions of it. It needs to be done without a pen and a paper and just using mental math. Each gamified question should test the same skills the original question is testing.

Important - the original question is harder and needs a pen and a paper to solve as it has multiple steps. The gamified version is much simpler and just involves 1 step and can be done mentally.

I have shared practice questions for you to learn below:

Each question has 6 points :
the original GMAT question,
the concept column 1 tests,
the gamified easy version of the original,
the column 3 it tests,
the gamified harder version of the original - this needs to be a harder version of the gamified question - slightly harder, but still solvable without a pen and a paper. it just needs to be a little harder to do mentally. ,
the concept column 5 tests.

Examples:

GMAT Question: If 3x - 5 = 4x + 7, what is the value of x?
The concept it is using is: Algebra - Linear Equations
Its gamified version is: If 5x = 25, what is x?
The gamified concept is: Linear Equations
Its hard gamified version is: If 7x = 56, what is x?
The hard gamified concept is: Linear Equations
----------------------------------------
GMAT Question: A bag contains 4 red, 5 blue, and 3 green marbles. If one is selected at random, what is the probability it is not red?
The concept it is using is: Probability
Its gamified version is: What is the probability of not rolling a 6 on a 6-sided die?
The gamified concept is: Probability
Its hard gamified version is: What is the probability of not rolling a 6 or a 5 on a fair die?
The hard gamified concept is: Probability
----------------------------------------
GMAT Question: A triangle has two sides of 5 and 12 units. If the angle between them is 90°, what is the area of the triangle?
The concept it is using is: Geometry - Right Triangle
Its gamified version is: What’s the area of a triangle with base 6 and height 4?
The gamified concept is: Geometry
Its hard gamified version is: What's the area of a triangle with base 9 and height 8?
The hard gamified concept is: Geometry
----------------------------------------
GMAT Question: A product is marked up by 25% and then given a 20% discount. What is the final price of a $100 item?
The concept it is using is: Percentages
Its gamified version is: What is 80% of 125?
The gamified concept is: Percentages
Its hard gamified version is: What is 85% of 200?
The hard gamified concept is: Percentages
----------------------------------------
GMAT Question: The average of 4 numbers is 26. If three of the numbers are 20, 28, and 30, what is the fourth?
The concept it is using is: Statistics - Mean
Its gamified version is: What is the mean of 15, 20, and 25?
The gamified concept is: Statistics
Its hard gamified version is: What is the mean of 10, 20, 30, and 40?
The hard gamified concept is: Statistics
----------------------------------------
GMAT Question: A car travels 80 miles in 1 hour and 20 minutes. What is its average speed in miles per hour?
The concept it is using is: Word Problems - Rate
Its gamified version is: A train travels 90 miles in 1.5 hours. What’s the speed?
The gamified concept is: Word Problems
Its hard gamified version is: A train travels 120 miles in 1.5 hours. What's its speed in mph?
The hard gamified concept is: Word Problems
----------------------------------------
GMAT Question: If x+16=7\sqrt(x + 16) = 7x+16?=7, what is the value of x?
The concept it is using is: Exponents & Roots
Its gamified version is: What is the square root of 64?
The gamified concept is: Roots
Its hard gamified version is: What is the square root of 81?
The hard gamified concept is: Roots
----------------------------------------
GMAT Question: If 2x - 3 < 9, what is the maximum integer value of x?
The concept it is using is: Inequalities
Its gamified version is: If x < 9 and x is an integer, what’s the highest possible value x could be?
The gamified concept is: Inequalities
Its hard gamified version is: If x < 12 and x is an integer, what's the highest possible value of x?
The hard gamified concept is: Inequalities
----------------------------------------
GMAT Question: If 12 pencils cost $18, what’s the cost of 5 pencils?
The concept it is using is: Ratios & Proportions
Its gamified version is: If 3 pencils cost $6, what is the cost of 1 pencil?
The gamified concept is: Proportions
Its hard gamified version is: If 5 pencils cost $15, what is the cost of 2 pencils?
The hard gamified concept is: Proportions
----------------------------------------
GMAT Question: What is the least common multiple of 12, 15, and 18?
The concept it is using is: Number Properties - LCM
Its gamified version is: What is the GCD of 16 and 24?
The gamified concept is: Number Properties
Its hard gamified version is: What is the GCD of 18 and 30?
The hard gamified concept is: Number Properties
----------------------------------------
GMAT Question: A rectangular garden is 8 m long and 5 m wide. If a 1-meter-wide path is built around the garden, what is the area of the path?
The concept it is using is: Geometry – Area & Perimeter
Its gamified version is: What is the area of a rectangle with length 7 and width 3?
The gamified concept is: Area of Rectangle
Its hard gamified version is: What is the area of a rectangle with length 9 m and width 7 m?
The hard gamified concept is: Area of Rectangle
----------------------------------------
GMAT Question: If a worker earns $12 per hour and works 45 hours a week, what’s his overtime pay if he gets 1.5x for hours beyond 40?
The concept it is using is: Word Problems – Work & Pay
Its gamified version is: If you earn $20 per hour, what do you earn in 3 hours?
The gamified concept is: Multiplication
Its hard gamified version is: If you earn $25 per hour, what do you earn in 8 hours?
The hard gamified concept is: Multiplication
----------------------------------------
GMAT Question: If x² - 5x + 6 = 0, what are the possible values of x?
The concept it is using is: Algebra – Quadratics
Its gamified version is: What are two numbers that multiply to 6 and add to 5?
The gamified concept is: Factor Matching
Its hard gamified version is: What are two numbers that multiply to 12 and add to 7?
The hard gamified concept is: Factor Matching
----------------------------------------
GMAT Question: A number is divisible by both 3 and 4. What is the smallest such number greater than 10?
The concept it is using is: Number Properties – LCM
Its gamified version is: What’s the LCM of 3 and 4?
The gamified concept is: LCM
Its hard gamified version is: What's the LCM of 4 and 6?
The hard gamified concept is: LCM
----------------------------------------
GMAT Question: A store increases a $60 item by 10% and then applies a 10% discount. What is the final price?
The concept it is using is: Percent Increase & Decrease
Its gamified version is: What is 10% of 90?
The gamified concept is: Percent
Its hard gamified version is: What is 15% of 120?
The hard gamified concept is: Percent
----------------------------------------
GMAT Question: If the average of five numbers is 18 and the first four add up to 76, what is the fifth number?
The concept it is using is: Statistics – Mean
Its gamified version is: What’s the average of 10, 20, 30?
The gamified concept is: Average
Its hard gamified version is: What's the average of 15, 25, 35?
The hard gamified concept is: Average
----------------------------------------
GMAT Question: A cylindrical tank has a radius of 3 meters and a height of 4 meters. What’s its volume? (Use ? = 3.14)
The concept it is using is: Geometry – Volume
Its gamified version is: What’s the area of a circle with radius 7? (Use ? = 3)
The gamified concept is: Circle Area
Its hard gamified version is: What's the area of a circle with radius 14? (Use Ï€ â‰ˆ 3.14)
The hard gamified concept is: Circle Area
----------------------------------------
GMAT Question: If a car travels at 72 km/h, how many meters does it travel in 5 seconds?
The concept it is using is: Rate – Unit Conversion
Its gamified version is: If something moves at 10 m/s, how far does it go in 6 seconds?
The gamified concept is: Speed = Distance / Time
Its hard gamified version is: If something moves at 12 m/s, how far in 7 seconds?
The hard gamified concept is: Speed = Distance / Time
----------------------------------------
GMAT Question: Simplify: (2x + 3)(x - 4)
The concept it is using is: Algebra – Binomial Expansion
Its gamified version is: What is 12 — 11?
The gamified concept is: Mental Multiplication
Its hard gamified version is: What is 13 Ã— 12?
The hard gamified concept is: Mental Multiplication
----------------------------------------
GMAT Question: If 5^x = 125, what is the value of x?
The concept it is using is: Exponents
Its gamified version is: What is 3^2?
The gamified concept is: Exponents
Its hard gamified version is: What is 4Â³?
The hard gamified concept is: Exponents
----------------------------------------
GMAT Question: The sum of three consecutive even integers is 78. What is the middle integer?
The concept it is using is: Number Properties – Consecutive Integers
Its gamified version is: What is the middle of 10, 12, and 14?
The gamified concept is: Number Series
Its hard gamified version is: What is the middle of 12, 14, and 16?
The hard gamified concept is: Number Series
----------------------------------------
GMAT Question: A person invests $5000 at an interest rate of 4% per year, compounded annually. How much money will the person have after 2 years?
The concept it is using is: Interest – Compound
Its gamified version is: What’s 4% of $50?
The gamified concept is: Percentage
Its hard gamified version is: What's 5% of $200?
The hard gamified concept is: Percentage
----------------------------------------
GMAT Question: A train travels 60 miles per hour for 2 hours, then 80 miles per hour for 1 hour. What is the average speed of the train?
The concept it is using is: Word Problems – Average Speed
Its gamified version is: A car travels 30 miles in 1 hour. What’s its average speed?
The gamified concept is: Average Speed
Its hard gamified version is: A car travels 40 miles in 1 hour. What's its average speed?
The hard gamified concept is: Average Speed
----------------------------------------
GMAT Question: A clock shows the time as 2:45. How many degrees are between the hour and minute hands?
The concept it is using is: Geometry – Angles
Its gamified version is: What’s the angle between the hour and minute hands at 3:00?
The gamified concept is: Clock Angles
Its hard gamified version is: What's the angle between the hour and minute hand at 3:30?
The hard gamified concept is: Clock Angles
----------------------------------------
GMAT Question: If 4x + 3 = 19, what is the value of x?
The concept it is using is: Algebra – Linear Equations
Its gamified version is: If 3x = 12, what’s x?
The gamified concept is: Solving for x
Its hard gamified version is: If 5x - 2 = 18, what is x?
The hard gamified concept is: Solving for x
----------------------------------------
GMAT Question: A pizza has a diameter of 12 inches. What is its radius?
The concept it is using is: Geometry – Circles
Its gamified version is: What’s the radius of a circle with a diameter of 8?
The gamified concept is: Circle Radius
Its hard gamified version is: What's the radius of a circle with diameter 18?
The hard gamified concept is: Circle Radius
----------------------------------------
GMAT Question: A book is sold for $10 and then discounted by 20%. What is the price after the discount?
The concept it is using is: Percent Discount
Its gamified version is: What’s 20% off $50?
The gamified concept is: Percent Calculation
Its hard gamified version is: What's 25% off $120?
The hard gamified concept is: Percent Calculation
----------------------------------------
GMAT Question: What is the sum of all prime numbers less than 20?
The concept it is using is: Number Properties – Primes
Its gamified version is: What is the sum of 2, 3, 5, and 7?
The gamified concept is: Prime Numbers
Its hard gamified version is: What is the sum of 11, 13, 17?
The hard gamified concept is: Prime Numbers
----------------------------------------
GMAT Question: A sequence follows the rule: 3, 6, 9, 12, … What is the 10th term?
The concept it is using is: Number Properties – Arithmetic Sequence
Its gamified version is: What’s the 5th term of the sequence: 2, 4, 6, 8, …?
The gamified concept is: Sequence
Its hard gamified version is: What's the 6th term of the sequence: 3, 6, 9, â€¦?
The hard gamified concept is: Sequence
----------------------------------------
GMAT Question: If x + y = 7 and x - y = 3, what are the values of x and y?
The concept it is using is: Algebra – System of Equations
Its gamified version is: If x + y = 10 and x - y = 4, what are x and y?
The gamified concept is: System of Equations
Its hard gamified version is: If x + y = 12 and x - y = 6, what are x and y?
The hard gamified concept is: System of Equations
----------------------------------------
GMAT Question: The ratio of the ages of two brothers is 3:4. If the older brother is 24 years old, how old is the younger brother?
The concept it is using is: Ratios
Its gamified version is: If the ratio of two numbers is 2:3 and one number is 6, what is the other number?
The gamified concept is: Ratios
Its hard gamified version is: If the ratio of two numbers is 5:6 and one number is 20, what is the other?
The hard gamified concept is: Ratios
----------------------------------------
GMAT Question: If 3x + 5 = 2x + 8, what is the value of x?
The concept it is using is: Algebra – Linear Equations
Its gamified version is: If 4x + 3 = 11, what is x?
The gamified concept is: Solving for x
Its hard gamified version is: If 5x - 2 = 18, what is x?
The hard gamified concept is: Solving for x
----------------------------------------
GMAT Question: A rectangle has a length of 5 cm and a width of 10 cm. If the length is doubled, what is the new area?
The concept it is using is: Geometry – Area
Its gamified version is: What’s the area of a square with side 4 cm?
The gamified concept is: Area of Square
Its hard gamified version is: What's the area of a square with side 6 cm?
The hard gamified concept is: Area of Square
----------------------------------------
GMAT Question: A person has 10 coins. If they are all dimes and quarters, and the total value is $2.40, how many dimes are there?
The concept it is using is: Word Problems – Coins
Its gamified version is: If you have 3 quarters, how much money do you have?
The gamified concept is: Coin Value
Its hard gamified version is: If you have 4 quarters, how much money do you have?
The hard gamified concept is: Coin Value
----------------------------------------
GMAT Question: A car’s value depreciates by 10% every year. If the car is worth $25,000 now, what will its value be after 2 years?
The concept it is using is: Percent Depreciation
Its gamified version is: What is 10% of $50?
The gamified concept is: Percent
Its hard gamified version is: What is 15% of 120?
The hard gamified concept is: Percent
----------------------------------------
GMAT Question: A farmer has a field that is 120 meters long and 80 meters wide. What is the perimeter of the field?
The concept it is using is: Geometry – Perimeter
Its gamified version is: What’s the perimeter of a rectangle with sides 4 and 6?
The gamified concept is: Perimeter
Its hard gamified version is: What's the perimeter of a rectangle with sides 12 and 8?
The hard gamified concept is: Perimeter
----------------------------------------
GMAT Question: The sum of two numbers is 16, and their difference is 4. What are the two numbers?
The concept it is using is: Algebra – System of Equations
Its gamified version is: If x + y = 9 and x - y = 3, what are x and y?
The gamified concept is: System of Equations
Its hard gamified version is: If x + y = 12 and x - y = 6, what are x and y?
The hard gamified concept is: System of Equations
----------------------------------------
GMAT Question: If a car travels 75 miles in 1 hour 15 minutes, what is its average speed in miles per hour?
The concept it is using is: Rate – Average Speed
Its gamified version is: If a car travels 60 miles in 1 hour, what is its speed?
The gamified concept is: Speed
Its hard gamified version is: If a car travels 90 miles in 1.5 hours, what's its speed?
The hard gamified concept is: Speed
----------------------------------------
GMAT Question: A triangle has two sides of length 6 and 8. What is the length of the hypotenuse?
The concept it is using is: Geometry – Pythagorean Theorem
Its gamified version is: What is the hypotenuse of a 3-4-5 triangle?
The gamified concept is: Pythagoras Theorem
Its hard gamified version is: What is the hypotenuse of a right triangle with sides 5 and 12?
The hard gamified concept is: Pythagoras Theorem
----------------------------------------
GMAT Question: A number is decreased by 15% and then increased by 20%. What is the overall percentage change?
The concept it is using is: Percent Change
Its gamified version is: If a number is increased by 10%, then decreased by 10%, what’s the overall change?
The gamified concept is: Percent Change
Its hard gamified version is: If a number is increased by 20%, then decreased by 10%, what's the net change?
The hard gamified concept is: Percent Change
----------------------------------------
GMAT Question: If 3x + 2y = 7 and x = 2, what is the value of y?
The concept it is using is: Algebra – Substitution
Its gamified version is: If x + y = 5 and x = 3, what is y?
The gamified concept is: Substitution
Its hard gamified version is: If 2x + y = 10 and x = 3, what is y?
The hard gamified concept is: Substitution
----------------------------------------
GMAT Question: A store sells a shirt for $40 and gives a 25% discount. What is the sale price of the shirt?
The concept it is using is: Percent Discount
Its gamified version is: What’s 20% off $50?
The gamified concept is: Percent Calculation
Its hard gamified version is: What's 25% off $120?
The hard gamified concept is: Percent Calculation
----------------------------------------
GMAT Question: If 4x - 7 = 9, what is the value of x?
The concept it is using is: Algebra – Linear Equations
Its gamified version is: If 2x + 3 = 7, what is x?
The gamified concept is: Solving for x
Its hard gamified version is: If 5x - 2 = 18, what is x?
The hard gamified concept is: Solving for x
----------------------------------------
GMAT Question: A swimming pool is 10 meters long, 6 meters wide, and 2 meters deep. What is its volume?
The concept it is using is: Geometry – Volume
Its gamified version is: What is the volume of a cube with side length 3?
The gamified concept is: Volume of Cube
Its hard gamified version is: What is the volume of a cube with side length 4?
The hard gamified concept is: Volume of Cube
----------------------------------------
GMAT Question: What is the total cost of 3 items, each priced at $15, with a 5% sales tax?
The concept it is using is: Word Problems – Taxes
Its gamified version is: What is the total cost of two items costing $5 each, with 10% tax?
The gamified concept is: Taxes
Its hard gamified version is: What is the total cost of three items costing $25 each with 10% tax?
The hard gamified concept is: Taxes
----------------------------------------
GMAT Question: If x + 4 = 12, what is the value of x?
The concept it is using is: Algebra – Linear Equations
Its gamified version is: If x + 5 = 8, what’s x?
The gamified concept is: Solving for x
Its hard gamified version is: If 5x - 2 = 18, what is x?
The hard gamified concept is: Solving for x
----------------------------------------
GMAT Question: A student scored 80, 85, and 90 on three exams. What is the student’s average score?
The concept it is using is: Statistics – Mean
Its gamified version is: What’s the average of 10, 20, and 30?
The gamified concept is: Average
Its hard gamified version is: What's the average of 15, 25, 35?
The hard gamified concept is: Average
----------------------------------------
GMAT Question: A store sells 3 apples for $2. What is the price of 9 apples?
The concept it is using is: Word Problems – Proportions
Its gamified version is: If 4 pencils cost $3, how much do 12 pencils cost?
The gamified concept is: Proportions
Its hard gamified version is: If 5 pencils cost $15, what is the cost of 2 pencils?
The hard gamified concept is: Proportions
----------------------------------------
GMAT Question: A triangle has sides of length 7, 24, and 25. Is this a right triangle?
The concept it is using is: Geometry – Pythagorean Theorem
Its gamified version is: Are the sides 3, 4, and 5 of a right triangle?
The gamified concept is: Pythagoras Theorem
Its hard gamified version is: What is the hypotenuse of a right triangle with sides 5 and 12?
The hard gamified concept is: Pythagoras Theorem
----------------------------------------


Learn from these questions and give me the 3rd point that is the gamified version for the dataset I have provided.

"""

  prompt = prompt.format(question=question)

  gpt_data = {"messages": [
      {"role": "system", "content": "You are a GMAT question gamifier."},
      {"role": "user", "content": prompt}
  ]}

  return gpt_data

# print(apply_prompt_template(dataset_train.iloc[0], test=False))
print(apply_prompt_template(dataset.iloc[0], test=False)["messages"][0]["content"])
print(apply_prompt_template(dataset.iloc[0], test=False)["messages"][1]["content"])

dataset["gpt_data"] = dataset.apply(apply_prompt_template, axis=1)

"""Now generate GPT responses."""

client = OpenAI(api_key=SECRET_KEY)

gpt_responses = []
gpt_logprobs = []
gpt_probs = []
for prompt in tqdm(dataset["gpt_data"].values, total=len(dataset)):

  completion = client.chat.completions.create(
      model="gpt-4o-mini-2024-07-18",
      messages=prompt["messages"],
      temperature=1,
      # max_tokens=2,
      top_p=1,
      frequency_penalty=0,
      presence_penalty=0,
      logprobs=True,
      top_logprobs=1,
    )

  gpt_output = completion.choices[0].message.content
  gpt_logprob = completion.choices[0].logprobs.content[0].logprob

  gpt_responses.append(gpt_output.strip())
  gpt_logprobs.append(gpt_logprob)

dataset["gpt_response"] = gpt_responses
dataset

"""Now do the GPT-as-a-judge evaluation."""

def apply_prompt_template(sample, test=False):
  question = sample["question"]
  gpt_question = sample["gpt_response"]

  prompt = f"""Here are two questions:

Question 1:

{{question1}}

Question 2:

{{question2}}

Do questions 1 and 2 test the similar skills? Respond with "yes" or "no".

Answer:  """

  prompt = prompt.format(question1=question, question2=gpt_question)

  gpt_data = {"messages": [
      {"role": "system", "content": "You are a GMAT question skill comparer."},
      {"role": "user", "content": prompt}
  ]}

  return gpt_data

# print(apply_prompt_template(dataset_train.iloc[0], test=False))
print(apply_prompt_template(dataset.iloc[0], test=False)["messages"][0]["content"])
print(apply_prompt_template(dataset.iloc[0], test=False)["messages"][1]["content"])

dataset["gpt_judge_data"] = dataset.apply(apply_prompt_template, axis=1)

client = OpenAI(api_key=SECRET_KEY)

gpt_responses = []
gpt_logprobs = []
gpt_probs = []
for prompt in tqdm(dataset["gpt_judge_data"].values, total=len(dataset)):

  completion = client.chat.completions.create(
      model="gpt-4o-mini-2024-07-18",
      messages=prompt["messages"],
      temperature=1,
      # max_tokens=2,
      top_p=1,
      frequency_penalty=0,
      presence_penalty=0,
      logprobs=True,
      top_logprobs=1,
    )

  gpt_output = completion.choices[0].message.content
  gpt_logprob = completion.choices[0].logprobs.content[0].logprob

  gpt_responses.append(gpt_output.strip())
  gpt_logprobs.append(gpt_logprob)

dataset["gpt_judge_response"] = gpt_responses
dataset